file_mappings:
  "lista precios repuestos octubre 2025.pdf": "BERTINI_PDF"

providers:
  ROTAR:
    type: generic
    anchor:
      pattern: "CODIGO"
    mapping:
      SKU: "CODIGO"
      DESCRIPCION: "DESCRIPCION"
      PRECIO: "PRECIO"
    defaults:
      MONEDA: "USD"
      PROVEEDOR: "ROTAR"
  BERTINI:
    type: generic
    anchor:
      pattern: "codigo"
      row: 10
    mapping:
      SKU: "codigo"
      DESCRIPCION: "denominacion"
      PRECIO: "precio"
    defaults:
      MONEDA: "ARS"
      PROVEEDOR: "BERTINI"
  MG:
    type: generic
    anchor:
      pattern: "Articulo"
    mapping:
      SKU: "Articulo"
      DESCRIPCION: "Descripción"
      PRECIO: "Precio"
    defaults:
      MONEDA: "USD"
      PROVEEDOR: "MG"
  OH GARCIA:
    type: layout
    params:
      y_threshold: 2
      price_x_min: 450
      sku_x_max: 140
    mapping:
      SKU: 0
      DESCRIPCION: 1
      PRECIO: 2
    defaults:
      MONEDA: "ARS"
      PROVEEDOR: "OH GARCIA"
  ARAG:
    type: generic
    mapping:
      SKU: "codigo"
      DESCRIPCION: "descripcion"
      PRECIO: "lista pesos"
    defaults:
      MONEDA: "ARS"
      PROVEEDOR: "ARAG"
  BERTINI_PDF:
    type: layout
    params:
      y_threshold: 5
      price_x_min: 500
      sku_x_max: 100
    mapping:
      SKU: 0
      DESCRIPCION: 1
      PRECIO: 3
    defaults:
      MONEDA: "ARS"
      PROVEEDOR: "BERTINI"
